### ISSUE TITLE
Crash Case EventSendRevealSecretAfter

### ISSUE THREAD

**Issue by dognie** [SmartMeshFoundation/SmartRaiden#12]
# Feature
EventSendRevealSecretAfter
# Scenario
Route:Alice->Bob->Charle->Dave
Alice tx to Dave 20token, Charle Crash occurs after sending RevealSecret

- Reconnect before `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendRevealSecretAfter_BR.png)

- Reconnect after `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendRevealSecretAfter_AR.png)

**Comment by Liamgettingbetter** [comment]
2. Reconnect after `Expiration` 

This case, much like cases above, is that Alice sends a `MediatedTransfer` to Dave via Bob and Charlie. Finally, Dave has received this transfer. 

Currently, the channel states are

- In channel (Alice, Bob), there are 20 tokens hash-locked.
- In channel (Bob, Charlie), there are 20 tokens hash-locked.
- In channel (Charlie, Dave), there are 20 tokens hash-locked.

At the time Dave gets this `MediatedTransfer` from Alice, he enables to request secret so that 20 tokens can be funded into his account. So Dave asks for the secret via a `SecretRequest` to Alice. And Alice, as sure, replies her secret to Dave. Finally, Dave gets the secret.

After that, by a `RevealSecret`, Dave reveals his secret to Charlie so that Charlie can unlock 20 tokens in channel (Charlie, Dave). However, after Charlie receives this secret, she gets crashed down after she has reveal this secret to Bob. For Dave has no response from Charlie, he has to keep trying to send `RevealSecret` to Charlie. 

But Charlie still gets disconnected, Dave has no way but register his secret on chain to protect his own interest. Via a `RegisterSecret`, this secret has been registered on chain. 

Alice starts to send `Unlock` to Bob, telling him that tokens that has been unlocked, and Bob feeds her an ACK. Meanwhile, Bob unlocks his token in channel (Bob, Charlie) via a `Unlock` to Charlie. While Charlie has not yet turned online, this process remains till Charlie resumes. 

When Charlie restores the network connection of hers, she sends a `Unlock` to Dave in case that tokens hash-locked in channel (Charlie, Dave) have been unlocked. Then Dave replies with an ACK meaning that he has received that. 

As a result, Charlie sends an ACK to Bob. Till now, transaction succeeds.
