### ISSUE TITLE
Crash Case EventSendAnnouncedDisposedBefore

### ISSUE THREAD

**Issue by dognie** [SmartMeshFoundation/SmartRaiden#13]
# Feature
EventSendAnnouncedDisposedBefore
# Scenario
Route:Alice->Bob->Charle->Dave
Alice tx to Dave 60token, Charle Crash without sending AnnouncedDisposed

- Reconnect before `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendAnnouncedDisposedBefore_BR.png)

- Reconnect after `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendAnnouncedDisposedBefore_AR.png)

**Comment by Liamgettingbetter** [comment]
## Case Description

In our case, Alice prepares to send 60 tokens to Dave via multiple `MediatedTransfer`s. However, due to the reason that Charlie has no sufficient fund in channel (Charlie, Dave), which means the transfer cannot be processed and with no way Charlie has to relinquish this transfer via a `AnnouncedDisposed`. 

In this phase, all channel states are like below. 

- In channel (Alice, Bob), there are 60 tokens with a hash lock.
- In channel (Bob, Charlie), there are 60 tokens that are hash-locked.
- In channel (Charlie, Dave), there are no transfer of token. 

Charlie, then is about to send a `AnnouncedDisposed` to Bob who is informed that she is lack of fund to process this transfer. However, faulty condition occurs and leads to Charlie disconnecting from the network. And Bob has to send multiple `MediatedTransfer` to Charlie for he gets no response from Charlie.

With luck, soon enough Charlie gets on track again, and she receives those messages from Bob. Charlie then returns an ACK to Bob. After that, she does nothing but waits for this transfer expires. 

As soon as the transfer expires, Alice sends a `RemoveExpiredHashlock` to Bob denoting that she is about to give up and remove those expired hash locks, and as to Bob, once he knows that, he would replies an ACK. 

This process continues till Charlie receives a `RemoveExpiredHashlock` from Bob. Once she is informed by that and replies with an ACK, the whole transaction completes with failure and there are no tokens that are still hash locked.

**Comment by Liamgettingbetter** [comment]
2. Reconnect after `Expiration`.

Same as the above one, Alice wishes to send Dave 60 tokens via `MediatedTransfer`, and Charlie has no such amount of tokens deposited in her channel. Charlie hopes to give up this transfer with a `AnnouncedDisposed` to Bob. Only a tiny difference between this case and one that above, that is, Charlie reconnects to the network over a long haul, even after all these transfers get expired.

In this case, all channel states are 

- In channel (Alice, Bob), there are 60 tokens hash locked.
- In channel (Bob, Charlie), there are 60 tokens hash locked.
- In channel (Charlie, Dave), there are no tokens being locked.

As for Charlie, because she gets crashed down prior to her sending `AnnouncedDisposed`, Bob receives nothing and he has to keep feed `MediatedTransfer` to Charlie. From now on, the entire transfer process is deadlocked. 

After some amount of blocks, this transfer gets expired. 

Then Alice sends a `RemoveExpiredHashlock` to Bob, and Bob, as a notification of receiving that, responds with an ACK. After getting this message, Bob also sends a 'RemoveExpiredHashlock` to Charlie. For that Charlie is still offline at this moment, though reluctant, Bob has to keep feeding `RemoveExpiredHashlock` until Charlie gets back online again. 

Once Charlie restores her online status, she starts to reply all messages she received with ACKs. In the end, this transaction completes with failure, and there is no token that is hash locked.
