### ISSUE TITLE
Crash Case EventSendAnnouncedDisposedAfter

### ISSUE THREAD

**Issue by dognie** [SmartMeshFoundation/SmartRaiden#14]
# Feature
EventSendAnnouncedDisposedBefore
# Scenario 
Route:Alice->Bob->Charle->Dave
Alice tx to Dave 20token, Charle Crash occurs after sending AnnouncedDisposed

- Reconnect before `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendAnnouncedDisposedAfter_BR.png)

- Reconnect after `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendAnnouncedDisposedAfter_AR.png)

**Comment by Liamgettingbetter** [comment]
## Case Description 

1. Reconnects before `Expiration` 

In this case, Alice wishes to send Dave 20 tokens via `MediatedTransfer`s. But Charlie has no sufficient fund in channel (Charlie, Dave) so she cannot process this transfer. For this reason, Charlie has to send a `AnnouncedDisposed` message to Bob to inform his about her situation. However, crash occurs right after Charlie sends this message to Bob. And Bob keeps feeding `MediatedTransfer` to Charlie.

After a short while, Charlie restores online again. Then Charlie finishes what she can do after replying an ACK to Bob. Till now, all channel participants waits for transfer gets expired.

Once transfer expired, Alice sends a `RemoveExpiredHashlock` to Bob, and Bob continues this process after Charlie replies him an ACK. At that time, transaction completes with failure and no hash lock about this transfer exists.

**Comment by Liamgettingbetter** [comment]
2. Reconnect after `Expiration` 

Also, Alice wishes to send Dave 20 tokens via indirect payment channels among Alice, Bob, Charlie, and Dave. In this case, Alice feeds a `MediatedTransfer` to Bob, Bob then transfers this `MediatedTransfer` to Charlie. However, unfortunately, in channel (Charlie, Dave) there is no sufficient funds deposited, hence Charlie can not further this message to Dave. 

In order to continue this transaction, Charlie has to give up this transfer by returning a message `AnnouncedDisposed` to Alice. 

At this spot, something happens and to one's surprise Charlie crashes down as soon as he has finished `AnouncedDisposed` to Alice. 

Right now, our channel states are 


- In channel (Alice, Bob), 20 tokens have been hash locked.
- In channel (Bob, Charlie), 20 tokens have been hash locked.
- In channel (Charlie, Dave), there are no token being locked. 

For the reason that Bob has no response from Charlie, he has to keep feeding `MediatedTransfer`s to Dave until all transfers in these channels have expired.

Some amount of blocks later, all these payment channels have expired. Then Alice starts to feed `RemoveExpiredHashlock` to Bob, once Bob has received it, he feeds an ACK back to Alice. And Bob, then begin to feed this `RemoveExpiredHashlock` to Charlie, but at that time Charlie still is out of track. Bob keeps this process till Charlie resumes.

Once Charlie resumes, she returns an ACK to notify Bob that she has got his message. Till now, this transaction completes with failure and all tokens deposited in these channel get unlocked.
