### ISSUE TITLE
Crash Case EventSendAnnouncedDisposedResponseAfter

### ISSUE THREAD

**Issue by dognie** [SmartMeshFoundation/SmartRaiden#17]
# Feature
EventSendAnnouncedDisposedResponseAfter
# Scenario
Route:Alice->Bob->Charle->Dave
Alice tx to Dave 60token, Bob Crash occurs after sending AnnounceDisposedResponse

- Reconnect before `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendAnnouncedDisposedResponseAfter_BR.png)

-  Reconnect after `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendAnnouncedDisposedResponseAfter_AR.png)

**Comment by Liamgettingbetter** [comment]
## Case Description

1. Reconnect before `Expiration`

In this case, Dave will get a transfer of 60 tokens from Alice, and no direct path between Alice and Dave exists. And as a roundabout, there is an indirect path among Alice, Bob, Charlie, and Dave, which we can use to complete this transfer. 

To begin with, Alice sends a `MediatedTransfer` to Bob. And Bob then further this `MediatedTransfer` to Charlie. Once Charlie receive this transfer, she knows that due to a lack of fund deposited in channel (Chalie, Dave), she can't further this transfer. So she decides to tell Bob about this situation with an `AnnouncedDisposed` message. 

Once Bob knows that Charlie can't further this transfer to Dave, he begins to notify Alice with this information via a `AnnouncedDisposed` message. However, right after Bob sends out `AnnouncedDisposed`, he gets crashed down. 

At that time, our channel states are 

- In channel (Alice, Bob), there are 60 tokens hash locked.
- In channel (Bob, Charlie), there are 60 tokens hash locked.
- In channel (Charlie, Dave), no token has been hash-locked.

With certainty, Alice receives this message from Bob of `AnnouncedDisposed`. Then Alice tries to tell Bob that she is about to abandon this transfer and unlock those 60 tokens locked in channel between her and Bob, via a message named `AnnounceDisposedResponse`. Meanwhile, Charlie keep feeding `AnnounceDisposed` messages to Bob. 

After a certain amount of blocks later, Bob restores his connection and transfer process is still valid. Bob learns about that Alice has sent a `AnnounceDisposedResponse` to him, then he tells Charlie that 
Alice approves to abandon this transfer and unlocks tokens via a `AnnounceDisposedResponse`. After a while, Charlie replies an ACK. Then Bob refers this message to Alice. 

Till now, channel states are 

- In channel (Alice, Bob), hash locks of 60 tokens have been removed.
- In channel (Bob, Charlie), hash lock of 60 tokens have been removed.
- In channel (Charlie, Dave), hash lock of 60 tokens have been removed.

Bob also receives several messages from Charlie which are `AnnouncedDisposed`, then he replies these messages with an ACK. 

In the end, the trial of token transfer fails and tokens locked in these channels reverts to their original account.

**Comment by Liamgettingbetter** [comment]
2. Reconnect after `Expiration` 

Also, Dave will receive 60 tokens from Alice via multiple `MediatedTransfer`s. To start, Alice sends out a `MediatedTransfer` to Bob, and Bob refers this `MediatedTransfer` to Charlie. While Charlie receives this message, she finds that there is lack of tokens to further this transfer. As a result, Charlie wishes to inform initiator of the transfer to abandon it, and she sends out a `AnnouncedDisposed` message to Bob. 

Once Bob receives this message from Charlie, immediately he informs Alice via a `AnnounceDisposed` message, and right at the moment Bob feeds a `AnnounceDisposedResponse` to Charlie, he accidentally crashes down. Both Alice and Charlie have no idea about that, and they keeps feeding messages like `AnnounceDisposedResponse` and `AnnounceDisposed`, respectively till Bob resumes. 

At that moment, channel states are 

- In channel (Alice, Bob), 60 tokens are hash locked.
- In channel (Bob, Charlie), 60 tokens are hash locked.
- In channel (Charlie, Dave), no token is hash locked.

Unfortunately, Bob does not restore his connection until this transfer gets expired. Once Bob resumes, he finds that this transfer has expired and that he has received messages both from Alice and Charlie. Then Bob sends out a `AnnouncedDisposedResponse` to Charlie and then Charlie replies with an ACK to tell Bob she knows that 60 tokens locked in channel (Bob, Charlie) have been unlocked. After that, Bob returns to Alice with an ACK. Because Bob also receives several `AnnouncedDisposed` message from Charlie, so he needs to reply Charlie with an ACK. Till now, this transfer process completes with failure and all tokens have been unlocked.
