### ISSUE TITLE
Crash Case EventSendMediatedTransferAfter

### ISSUE THREAD

**Issue by dognie** [SmartMeshFoundation/SmartRaiden#8]
# Feature
EventSendMediatedTransferAfter

# Scenario
Route:Alice->Bob->Charle->Dave
Alice tx to Dave 20token, Charle send MediatedTransfer before crash

- Reconnect before `Expiration`
![EventSendMediatedTransferAfter_BR](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendMediatedTransferAfter_BR.png)

- Reconnect after `Expiration`
![EventSendMediatedTransferAfter_AR](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendMediatedTransferAfter_AR.png)

**Comment by dognie** [comment]
# 场景：在`Expiration`过期前重启
虽然符合崩溃恢复的原则：
- 不丢钱
- 通道不作废

但是有一些问题我依然不明白：
- `Secret`已经被Dave在链上注册，且大家都能查询到，为什么都不会`Ulock`，而是要等到`Expired`过了后再Remove expired hashlock

**Comment by Liamgettingbetter** [comment]
## Case Description
*** 
1. Reconnect before `Expiration` 

In our case, Alice, as a initiator, wishes to give Dave 20 tokens by off-chain payment channel. Nevertheless, Alice finds that she has no direct access to Dave, and meanwhile, she has a direct payment channel to Bob who can transfer this payment to Dave. 

Alice then sends a `MediatedTransfer` with a hash time lock in channel (Alice, Bob). Bob receives it after a while, and he transfers it to Charlie. Successfully, Charlie also gets this `MediatedTransfer`. 

After Charlie makes this transfer to Dave, in channel (Charlie, Dave), she goes offline. 

As to Bob, without any notice from Charlie, he has no idea whether Charlie has received his message. So, Bob will continuously send `MediatedTransfer` to Dave till Charlie sends an ACK back. 

As to Charlie, after she goes out of track, she gets reconnected to this network prior to `Expiration`. At that time, because she has received multiple `MediatedTransfer` from Bob, then she sends a ACK back to him. After that, Charlie then sends another `MediatedTransfer` to Dave. 

Once Dave gets this `MediatedTransfer`, he wishes to know the Secret in order to unlock tokens. Hence, he sends a `SecretRequest` to Alice. Alice then sends back a `RevealSecret` to Dave, with no obstacle. 

At the moment that Dave gets secret, he is about to send `RevealSecret` to Charlie, in order that he can unlock 20 tokens in channel (Charlie, Dave). And once Charlie receives that, she notifies Dave with an ACK meaning that she has got this secret. But if Charlie, as a potentially fraudulent actor, does not want to send `Unlock` to Dave and does nothing. After a few blocks later, Dave feels that something goes wrong, and he plans to do a `RegisterSecret` on chain. Then every participant can know the secret but everyone of them gives no `Unlock` to their channel counterparts. 

Then all these transfers gets expired. 

Because of that, Alice has to send `RemoveExpiredHashlock` to Bob, with a notification of ACK from Bob. Bob, Charlie continues this process till Dave sends an ACK back to Charlie. Now, they've done all the work and transaction fails.

**Comment by Liamgettingbetter** [comment]
2. Reconnect after `Expiration`

The same situation as above, with only a difference that Charlie goes on track after all these transfers get expired. 

In this case, 

- In channel (Alice, Bob), 20 tokens are locked.
- In channel (Bob, Charlie), 20 tokens are locked.

Because Dave gets no `MediatedTransfer` from Charlie, he has no idea that Alice wishes to send 20 tokens to him. As a result, Dave is not going to request the secret. 

All these transfers gets expired. 

Alice then sends a `RemoveExpiredHashlock` to Bob, and Bob responds to her with an ACK. As to Charlie, because she is still out of network, with no doubt she can' t reply any message from Bob. So Bob has to continue sending `RemoveExpiredHashlock` to Charlie till Charlie replies with an ACK to inform that she gets this message. 

After a certain amount of block time, all these expired hash locks gets removed. Charlie goes online, and she finds that Bob has sent her with multiple `RemoveExpiredHashlock`s, she then sends an ACK to Bob but there is no lock to be removed. This transaction fails.

**Comment by dognie** [comment]
## ~~Knowing secret will not send unlock problem.~~
The problem has been solved after update the contract.
