### ISSUE TITLE
Crash Case EventSendSecretRequestBefore

### ISSUE THREAD

**Issue by dognie** [SmartMeshFoundation/SmartRaiden#9]
# Feature
EventSendSecretRequestBefore

# Scenario
Route:Alice->Bob->Charle->Dave
Alice tx to Dave 20token,Dave Crash without sending SecretRequest

- Reconnect before `Expiration`
![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendSecretRequestBefore_BR.png)

- Reconnect after `Expiration`

![](https://raw.githubusercontent.com/SmartMeshFoundation/SmartRaiden/master/docs/images/EventSendSecretRequestBefore_AR.png)

**Comment by Liamgettingbetter** [comment]
## Case Description

1. Reconnect before `Expiration`. 

In our case, Alice wishes to send 20 tokens to Dave. By a `MediatedTransfer` with 20 tokens hash-locked in it. Bob, as usual, transfer this `MediatedTransfer` to Charlie. As to Charlie, at the time she has received this transfer, with no hesitation, he sends it to Dave. This process operates successfully. 

Right now, all channel states are

- In channel (Alice, Bob), 20 tokens are hash locked.
- In channel (Bob, Charlie), 20 tokens are hash locked.
- In channel (Charlie, Dave), 20 tokens are hash locked.

Once Dave has received `MediatedTransfer` from Alice, he will be able to request secret of this MediatedTransfer. However, Dave gets disconnected from the network for some reasons, prior to his sending `SecretRequest` to Alice. In response to that, Charlie has to send `MediatedTransfer` to Dave till Dave replies with an ACK. 

Fortunately, this time it seems like Dave resumes very quickly. Before all these transfers get expired, Dave replies an ACK to Charlie denoting that he has already got all these messages from Charlie. After that, Dave starts to send `SecretRequest` to Alice, and Alice, with no doubt, reveals her secret by replying a `RevealSecret` to Dave. 

When Dave has got the secret from Alice, he can also reveal this secret to Charlie, in order to unlock his deserved token by sending `RevealSecret` to Charlie. After Charlie confirms that, she is willing to send `Unlock` to Dave, informing that hash lock in this transfer has been unlocked. 

As to Charlie, she can also continue this process, which means Charlie reveals her secret to Bob and Bob confirms that and unlocks transfer's hash lock. 

This process continues until all these hash locks have been unlocked. And at that time, transaction succeeds.

**Comment by Liamgettingbetter** [comment]
2. Reconnect after `Expiration`

In this case, Dave gets down once he has received `MediatedTransfer` from Alice. However, this time Dave takes a long haul to get online even at that time, all these transfers get expired. 

In detail, when Dave has received `MediatedTransfer`, he crashes with no message to anyone. Charlie continues to send `MediatedTransfer` to Dave. 

After a while, these transfers get expired. 

Alice send `RemoveExpiredHashlock` to Bob, once Bob receives it, he sends an ACK back to Alice. As to Bob, he can transfer this `RemoveExpiredHashlock` to Charlie, and after Charlie receives that, she also replies with an ACK. 

However, because at that time, our dear Dave has not yet reconnected, Charlie has no way but continues to send `RemoveExpiredHashlock` till Dave gets back and makes a reply. 

Once Dave gets reconnected, he immediately replies an ACK to Charlie. Till now, all these transfer's hash locks have been removed. Transaction fails and all channel states revert back to ones that this transaction starts with.
